spring.application.name=simeioma
spring.datasource.url=jdbc:mysql://localhost:3306/simeioma
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=single007
spring.datasource.password=single007
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true